---
# Object Type 
# List with updated objects 
atr_interfaces/ObjectList list

# true if the objects are updated  
bool success 

# In case of error, we can provide feedback for the source 
atr_interfaces/ATRError error